package br.uff.ic.Prov_Viewer;

import br.uff.ic.Prov_Viewer.Input.Config;
import br.uff.ic.Prov_Viewer.Input.TSVReader;
import br.uff.ic.Prov_Viewer.Filter.Filters;
import br.uff.ic.Prov_Viewer.Filter.PreFilters;
import br.uff.ic.Prov_Viewer.Vertex.EntityVertex;
import br.uff.ic.Prov_Viewer.Vertex.AgentVertex;
import br.uff.ic.Prov_Viewer.Layout.Temporal_Layout;
import br.uff.ic.Prov_Viewer.Stroke.EdgeStroke;
import br.uff.ic.Prov_Viewer.Edge.Edge;
import br.uff.ic.Prov_Viewer.Vertex.VisualizationModes.VertexPainter;
import br.uff.ic.Prov_Viewer.Stroke.VertexStroke;
import br.uff.ic.Prov_Viewer.Vertex.VertexShape;
import br.uff.ic.Prov_Viewer.Vertex.Vertex;
import edu.uci.ics.jung.graph.DirectedGraph;
import edu.uci.ics.jung.graph.DirectedSparseMultigraph;
import edu.uci.ics.jung.graph.Graph;
import edu.uci.ics.jung.visualization.VisualizationViewer;
import edu.uci.ics.jung.visualization.control.CrossoverScalingControl;
import edu.uci.ics.jung.visualization.control.DefaultModalGraphMouse;
import edu.uci.ics.jung.visualization.control.ModalGraphMouse;
import edu.uci.ics.jung.visualization.control.ScalingControl;
import edu.uci.ics.jung.visualization.decorators.EdgeShape;
import edu.uci.ics.jung.visualization.decorators.ToStringLabeller;
import edu.uci.ics.jung.visualization.picking.PickedInfo;
import edu.uci.ics.jung.visualization.subLayout.GraphCollapser;
import edu.uci.ics.jung.visualization.util.PredicatedParallelEdgeIndexFunction;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Paint;
import java.awt.Stroke;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.commons.collections15.Predicate;
import org.apache.commons.collections15.Transformer;

/**
 * Prov Viewer GUI. Can be used as a Template.
 * @author kohwalter
 */
public class GraphFrame extends javax.swing.JFrame {
    static String filePath = "log.txt";
    static String tutorialPath = "tutorial.txt";
    final Set exclusions = new HashSet();
    
//    VisualizationViewer<Object, Edge> view;
//    Layout<Object, Edge> layout;
//    GraphCollapser gCollapser;
//    static DirectedGraph<Object,Edge> graph;
//    DirectedGraph<Object,Edge> collapsedGraph;
    
    DefaultModalGraphMouse mouse = new DefaultModalGraphMouse();
    boolean filterCredits = false;

    Variables variables = new Variables();
    Collapser collapser = new Collapser();
    Filters filter = new Filters();

    /**
     * Creates new form GraphFrame
     * @param graph 
     */
    public GraphFrame(DirectedGraph<Object, Edge> graph) {
        initComponents();
        initGraphComponent(graph);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        G7Days = new javax.swing.JButton();
        CollapseAgent = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Expand = new javax.swing.JButton();
        Collapse = new javax.swing.JButton();
        MouseModes = new javax.swing.JComboBox();
        FilterEdge01 = new javax.swing.JCheckBox();
        FilterNodeAgentButton = new javax.swing.JCheckBox();
        FilterEdgeNeutral = new javax.swing.JCheckBox();
        FilterNodeLonelyButton = new javax.swing.JCheckBox();
        FilterEdge02 = new javax.swing.JCheckBox();
        FilterEdge03 = new javax.swing.JCheckBox();
        FilterEdge04 = new javax.swing.JCheckBox();
        FilterEdge05 = new javax.swing.JCheckBox();
        FilterEdge06 = new javax.swing.JCheckBox();
        FilterEdge07 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EdgeLineShapeSelection = new javax.swing.JComboBox();
        StatusFilterBox = new javax.swing.JComboBox();
        ShowEdgeTextButton = new javax.swing.JCheckBox();
        FilterEdge09 = new javax.swing.JCheckBox();
        FilterEdge08 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FilterEdge11 = new javax.swing.JCheckBox();
        FilterEdge10 = new javax.swing.JCheckBox();
        FilterEdge12 = new javax.swing.JCheckBox();
        FilterEdge13 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        FilterList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prov Viewer");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        G7Days.setText("Granularity: 7 days");
        G7Days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G7DaysActionPerformed(evt);
            }
        });

        CollapseAgent.setText("CollapseAgent");
        CollapseAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollapseAgentActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Expand.setText("Expand");
        Expand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpandActionPerformed(evt);
            }
        });

        Collapse.setText("Collapse");
        Collapse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollapseActionPerformed(evt);
            }
        });

        MouseModes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Transforming", "Picking" }));
        MouseModes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MouseModesActionPerformed(evt);
            }
        });

        FilterEdge01.setText("Credits");
        FilterEdge01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge01ActionPerformed(evt);
            }
        });

        FilterNodeAgentButton.setText("Agents Vertices");
        FilterNodeAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterNodeAgentButtonActionPerformed(evt);
            }
        });

        FilterEdgeNeutral.setSelected(true);
        FilterEdgeNeutral.setText("Neutral");
        FilterEdgeNeutral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdgeNeutralActionPerformed(evt);
            }
        });

        FilterNodeLonelyButton.setText("Lonely Vertices");
        FilterNodeLonelyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterNodeLonelyButtonActionPerformed(evt);
            }
        });

        FilterEdge02.setText("Quality");
        FilterEdge02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge02ActionPerformed(evt);
            }
        });

        FilterEdge03.setText("Progress");
        FilterEdge03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge03ActionPerformed(evt);
            }
        });

        FilterEdge04.setText("Aid");
        FilterEdge04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge04ActionPerformed(evt);
            }
        });

        FilterEdge05.setText("Val");
        FilterEdge05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge05ActionPerformed(evt);
            }
        });

        FilterEdge06.setText("Discovery");
        FilterEdge06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge06ActionPerformed(evt);
            }
        });

        FilterEdge07.setText("Repair");
        FilterEdge07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge07ActionPerformed(evt);
            }
        });

        jLabel1.setText("Vertex Filter");

        jLabel2.setText("Display Edge");

        EdgeLineShapeSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "QuadCurve", "Line" }));
        EdgeLineShapeSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdgeLineShapeSelectionActionPerformed(evt);
            }
        });

        StatusFilterBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Morale", "Stamina", "Hours", "Weekend", "Credits", "Role" }));
        StatusFilterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusFilterBoxActionPerformed(evt);
            }
        });

        ShowEdgeTextButton.setText("Edge Text");
        ShowEdgeTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowEdgeTextButtonActionPerformed(evt);
            }
        });

        FilterEdge09.setText("TC");
        FilterEdge09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge09ActionPerformed(evt);
            }
        });

        FilterEdge08.setText("Bug");
        FilterEdge08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge08ActionPerformed(evt);
            }
        });

        jLabel3.setText("Attribute Status");

        jLabel4.setText("Edge Style");

        jLabel5.setText("Mouse Mode");

        FilterEdge11.setText("Stamina");
        FilterEdge11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge11ActionPerformed(evt);
            }
        });

        FilterEdge10.setText("Morale");
        FilterEdge10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge10ActionPerformed(evt);
            }
        });

        FilterEdge12.setText("Prototype");
        FilterEdge12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge12ActionPerformed(evt);
            }
        });

        FilterEdge13.setText("Negotiation");
        FilterEdge13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterEdge13ActionPerformed(evt);
            }
        });

        FilterList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        FilterList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FilterListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(FilterList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(G7Days)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CollapseAgent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(Collapse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Expand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FilterNodeLonelyButton)
                            .addComponent(FilterNodeAgentButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ShowEdgeTextButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilterEdge01)
                                    .addComponent(FilterEdgeNeutral))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilterEdge02)
                                    .addComponent(FilterEdge03))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilterEdge05)
                                    .addComponent(FilterEdge04))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilterEdge07)
                                    .addComponent(FilterEdge06))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilterEdge09)
                                    .addComponent(FilterEdge08))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FilterEdge10)
                                    .addComponent(FilterEdge11))))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Reset)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StatusFilterBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(FilterEdge12)
                    .addComponent(FilterEdge13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MouseModes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EdgeLineShapeSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CollapseAgent)
                                .addComponent(G7Days))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Collapse)
                                .addComponent(Expand)
                                .addComponent(Reset)))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(ShowEdgeTextButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FilterEdgeNeutral)
                            .addComponent(FilterEdge02)
                            .addComponent(FilterEdge04)
                            .addComponent(FilterEdge06)
                            .addComponent(FilterEdge08)
                            .addComponent(FilterEdge10)
                            .addComponent(FilterEdge12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FilterEdge03)
                                .addComponent(FilterEdge05)
                                .addComponent(FilterEdge07)
                                .addComponent(FilterEdge09)
                                .addComponent(MouseModes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FilterEdge11)
                                .addComponent(FilterEdge13))
                            .addComponent(FilterEdge01)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(FilterNodeAgentButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StatusFilterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdgeLineShapeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)))
                        .addComponent(FilterNodeLonelyButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-866)/2, (screenSize.height-738)/2, 866, 738);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * ================================================
     * Expand Button
     * ================================================
     */
    private void ExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpandActionPerformed
        Collection picked = new HashSet(variables.view.getPickedVertexState().getPicked());
        collapser.Expander(variables, filter, picked);
    }//GEN-LAST:event_ExpandActionPerformed
    /**
     * ================================================
     * Collapse Button
     * ================================================
     */
    private void CollapseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollapseActionPerformed
        //cannot use java generics type declarations with the graph collapser
        Collection picked = new HashSet(variables.view.getPickedVertexState().getPicked());
        collapser.Collapse(variables, filter, picked);
    }//GEN-LAST:event_CollapseActionPerformed
    /**
     * ================================================
     * Reset Button
     * ================================================
     */
    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        collapser.ResetGraph(variables, filter);
    }//GEN-LAST:event_ResetActionPerformed
    /**
     * ================================================
     * Select Mouse mode Button
     * ================================================
     */
    private void MouseModesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MouseModesActionPerformed
        String mode = (String)MouseModes.getSelectedItem();
        if(mode.equalsIgnoreCase("Picking"))
        {
             mouse.setMode(ModalGraphMouse.Mode.PICKING);
        }
        if(mode.equalsIgnoreCase("Transforming"))
        {
             mouse.setMode(ModalGraphMouse.Mode.TRANSFORMING);
        }
    }//GEN-LAST:event_MouseModesActionPerformed
    /**
     * ================================================
     * Collapse Agent's processes
     * ================================================
     */
    private void CollapseAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollapseAgentActionPerformed
        PickedInfo<Object> picked_state;
        picked_state = variables.view.getPickedVertexState();
        Object node = null;
        //Get the selected node
        for(Object z : variables.layout.getGraph().getVertices())
        {
            if (picked_state.isPicked(z))
            {
                node = z;
            }
        }
        //Select the node and its neighbors to be collapsed
        if(variables.layout.getGraph().getNeighbors(node) != null)
        {
            Collection picked = new HashSet(variables.layout.getGraph().getNeighbors(node));
            picked.add(node);
            if(!(node instanceof AgentVertex)) 
            {
                picked.removeAll(picked);
            }   
            collapser.Collapse(variables, filter, picked);
        }
    }//GEN-LAST:event_CollapseAgentActionPerformed
    /**
     * ================================================
     * Set week granularity Button
     * ================================================
     */
    private void G7DaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G7DaysActionPerformed
        collapser.ResetGraph(variables, filter);
        //Collapse agent's nodes 7 by 7
        for(Object z : variables.layout.getGraph().getVertices())
        {
            if(z instanceof AgentVertex)
            {
                collapser.Granularity(variables, filter, z, 7);
            }
        }      
    }//GEN-LAST:event_G7DaysActionPerformed
    /**
         * ================================================
         * Filtering credit edges
         * ================================================
         */
    private void FilterEdge01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge01ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge01ActionPerformed
    /**
         * ================================================
         * Filtering agent vertices
         * ================================================
         */
    private void FilterNodeAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterNodeAgentButtonActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterNodeAgentButtonActionPerformed
    /**
         * ================================================
         * Filtering black Edges (edges with 0)
         * ================================================
         */
    private void FilterEdgeNeutralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdgeNeutralActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdgeNeutralActionPerformed
    /**
         * ================================================
         * Filtering lonely vertices
         * ================================================
         */
    private void FilterNodeLonelyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterNodeLonelyButtonActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterNodeLonelyButtonActionPerformed
    /**
         * ================================================
         * Filtering Quality Edges
         * ================================================
         */
    private void FilterEdge02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge02ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge02ActionPerformed
    /**
         * ================================================
         * Filtering Progress Edges
         * ================================================
         */
    private void FilterEdge03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge03ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge03ActionPerformed
    /**
         * ================================================
         * Filtering Aid Edges
         * ================================================
         */
    private void FilterEdge04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge04ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge04ActionPerformed
    /**
         * ================================================
         * Filtering Val Edges
         * ================================================
         */
    private void FilterEdge05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge05ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge05ActionPerformed
    /**
         * ================================================
         * Filtering Discovery Edges
         * ================================================
         */
    private void FilterEdge06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge06ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge06ActionPerformed
    /**
         * ================================================
         * Filtering Prototype Edges
         * ================================================
         */
    private void FilterEdge07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge07ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge07ActionPerformed
    /**
         * ================================================
         * Edge Shape: Make it to be a line instead of quadratic curves
         * ================================================
         */
    private void EdgeLineShapeSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdgeLineShapeSelectionActionPerformed
        String mode = (String)EdgeLineShapeSelection.getSelectedItem();
        if(mode.equalsIgnoreCase("QuadCurve"))
        {
             variables.view.getRenderContext().setEdgeShapeTransformer(new EdgeShape.QuadCurve<Object,Edge>());
        }
        if(mode.equalsIgnoreCase("Line"))
        {
             variables.view.getRenderContext().setEdgeShapeTransformer(new EdgeShape.Line<Object,Edge>());
        }
        variables.view.repaint();
    }//GEN-LAST:event_EdgeLineShapeSelectionActionPerformed

    /**
         * ================================================
         * Status Filter box
         * ================================================
         */
    private void StatusFilterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusFilterBoxActionPerformed
        variables.SetMode((String)StatusFilterBox.getSelectedItem());
        VertexPainter.VertexPainter(variables.view, variables);
        variables.view.repaint();
    }//GEN-LAST:event_StatusFilterBoxActionPerformed
    /**
         * ================================================
         * Show edge text button
         * ================================================
         */
    private void ShowEdgeTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowEdgeTextButtonActionPerformed
        if(ShowEdgeTextButton.isSelected())
        {
           variables.view.getRenderContext().setEdgeLabelTransformer(new ToStringLabeller<Edge>()); 
        }
        else
        {
            //Show nothing
            variables.view.getRenderContext().setEdgeLabelTransformer(new Transformer<Edge, String>() {

                @Override
                public String transform(Edge i) {
                    return "";
                }
            });
        }
        variables.view.repaint();
    }//GEN-LAST:event_ShowEdgeTextButtonActionPerformed
    /**
         * ================================================
         * Filter bug edges button
         * ================================================
         */
    private void FilterEdge08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge08ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge08ActionPerformed
    /**
         * ================================================
         * Filter Test Case edges button
         * ================================================
         */
    private void FilterEdge09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge09ActionPerformed
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge09ActionPerformed
    
    private void FilterEdge11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge11ActionPerformed
        // TODO add your handling code here:
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge11ActionPerformed

    private void FilterEdge10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge10ActionPerformed
        // TODO add your handling code here:
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge10ActionPerformed

    private void FilterEdge12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge12ActionPerformed
        // TODO add your handling code here:
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge12ActionPerformed

    private void FilterEdge13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterEdge13ActionPerformed
        // TODO add your handling code here:
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterEdge13ActionPerformed

    private void FilterListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FilterListValueChanged
        // TODO add your handling code here:
        collapser.Filters(variables, filter);
    }//GEN-LAST:event_FilterListValueChanged

    /**
     * ================================================
     * Init Graph Component
     * ================================================
     */
    private void initGraphComponent(DirectedGraph<Object, Edge> graph) {

        Config.Initialize();
        filter.filteredGraph = graph;
        variables.collapsedGraph = graph;
        filter.FilterInit();
        /**
         * ================================================
         * Choosing layout
         * ================================================
         */
//        layout = new SpringLayout2<Object, Edge>(graph);
        
//        Layout<Object, Edge> layout = new CircleLayout<Object, Edge>(graph);
//        layout = new FRLayout<Object, Edge>(graph);
        variables.layout = new Temporal_Layout<Object, Edge>(graph);
//        layout = new FRLayout2<Object, Edge>(graph);
//        Layout<Object, Edge> layout = new ISOMLayout<Object, Edge>(graph);
//        layout = new ISOMLayout<Object, Edge>(graph);
//        layout = new KKLayout<Object, Edge>(graph);
//        Layout<Object, Edge> layout = new StaticLayout<Object, Edge>(graph);
//        layout.setSize(new Dimension(2000, 2000));
        /**
         * ================================================
         * VisualizationViewer<Node, Edge> view = new VisualizationViewer<Node, Edge>(layout);
         * ================================================
         */
        variables.view = new VisualizationViewer<Object, Edge>(variables.layout);
        final ScalingControl scaler = new CrossoverScalingControl();
        scaler.scale(variables.view, 1/2.1f, variables.view.getCenter());

        variables.gCollapser = new GraphCollapser(graph);
        
        final PredicatedParallelEdgeIndexFunction eif = PredicatedParallelEdgeIndexFunction.getInstance();
        // ================================================
        //        final Set exclusions = new HashSet();
        //testing for edge collapse
        eif.setPredicate(new Predicate() {
            @Override
            public boolean evaluate(Object e) {

                    return exclusions.contains(e);
            }});
        // ================================================
        variables.view.getRenderContext().setParallelEdgeIndexFunction(eif);
        
        variables.view.setBackground(Color.white);
        this.getContentPane().add(variables.view, BorderLayout.CENTER);
        /**
         * ================================================
         * Adding interaction via mouse
         * Commands: t for translate, p for picking
         * ================================================
         */
//        DefaultModalGraphMouse mouse = new DefaultModalGraphMouse();
        variables.view.setGraphMouse(mouse);
        variables.view.addKeyListener(mouse.getModeKeyListener());
        /**
         * ================================================
         * Add a listener for ToolTips
         * ================================================
         */
        variables.view.setVertexToolTipTransformer(new ToStringLabeller() {
            @Override
            public String transform(Object v) {
                    if(v instanceof Graph) {
                            return ("<html>" + ((Graph)v).getVertices().toString() + "</html>");
                    }
                    return ("<html>" + v.toString() + "</html>");
                    //return super.transform(v);
            }});
        /**
         * ================================================
         * Edge Tooltip
         * ================================================
         */
        variables.view.setEdgeToolTipTransformer(new Transformer<Edge,String>(){
        @Override
            public String transform(Edge n) 
            {
                return n.getDetails();
            }
        });
        /**
         * ================================================
         * Labeling Vertex
         * ================================================
         */
//        view.getRenderContext().setVertexLabelTransformer(new ToStringLabeller<Node>());
        variables.view.getRenderContext().setVertexLabelTransformer(new Transformer<Object, String>() {

                @Override
                public String transform(Object v) {
                    if(v instanceof Graph) {
                        for(Object vertex : ((Graph)v).getVertices())
                        {
                            if(vertex instanceof AgentVertex) {
                                return "<html><font size=\"10\">" + ((Vertex)vertex).getName();
                            }
                        }    
                    }
                    if(v instanceof EntityVertex) {
                        return "<html><font size=\"10\">" + String.valueOf(((Vertex)v).getDate());
                    }
                    return "";
                }
            });
        
        /**
         * ================================================
         * Vertex Stroke
         * ================================================
         */
        Transformer<Object, Stroke> nodeStrokeTransformer =  new Transformer<Object, Stroke>() {
            @Override
            public Stroke transform(Object v) {
                return VertexStroke.VertexStroke(v, variables.view, variables.layout);
        }};
        variables.view.getRenderContext().setVertexStrokeTransformer(nodeStrokeTransformer);
        /**
         * ================================================
         * Edge Stroke
         * ================================================
         */
        variables.FindMax(graph);
        Transformer<Edge, Stroke> edgeStrokeTransformer =  new Transformer<Edge, Stroke>() {
            @Override
            public Stroke transform(Edge e) {
                return EdgeStroke.StrokeByType(e, variables);
            }
        };
        variables.view.getRenderContext().setEdgeStrokeTransformer(edgeStrokeTransformer);
        /**
         * ================================================
         * Vertex Paint
         * ================================================
         */
        VertexPainter.VertexPainter(variables.view, variables);
        /**
         * ================================================
         * Edge Paint
         * ================================================
         */
        Transformer edgePainter = new Transformer<Edge,Paint>() {
            @Override
            public Paint transform(Edge edge) {
                return edge.getColor();
            }
        };  
        variables.view.getRenderContext().setEdgeDrawPaintTransformer(edgePainter);
        variables.view.getRenderContext().setArrowDrawPaintTransformer(edgePainter);
        variables.view.getRenderContext().setArrowFillPaintTransformer(edgePainter);

        /**
         * ================================================
         * Node Shape
         * ================================================
         */
        variables.view.getRenderContext().setVertexShapeTransformer(new VertexShape());

        //graphicsContext.fill(shape);
        PreFilters.PreFilter();
        //Initialize selected filters from the GUI
        collapser.Filters(variables, filter);
    }
    
    /**
     * Get Graph from TSVReader
     * @param path
     * @return 
     */
    public static DirectedGraph<Object,Edge> getGraph(String path) {
        DirectedGraph<Object,Edge> g = new DirectedSparseMultigraph<Object,Edge>();
        try {
        //    try {
        //        TSVReader tsvReader = new TSVReader("log.txt");
                TSVReader tsvReader = new TSVReader(path);
        //        for (Node node : tsvReader.getNodes()) {
        //            graph.addVertex(node.getID());
        //        }
                for (Edge edge : tsvReader.getEdges()) {
        //            g.addEdge(edge, edge.getSource().getID(), edge.getTarget().getID());
                    g.addEdge(edge, edge.getSource(), edge.getTarget());
                }
        //    } catch (URISyntaxException | IOException ex) {
        //        Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
        //    }
            
        } catch (URISyntaxException ex) {
            Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return g;
}
    /**
     * Main
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional)">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
                Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        Variables.graph = getGraph(filePath);
        java.awt.EventQueue.invokeLater(new Runnable() {
                
            @Override
                public void run() {
                    new GraphFrame(Variables.graph).setVisible(true);
                }
            });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Collapse;
    private javax.swing.JButton CollapseAgent;
    private javax.swing.JComboBox EdgeLineShapeSelection;
    private javax.swing.JButton Expand;
    public static javax.swing.JCheckBox FilterEdge01;
    public static javax.swing.JCheckBox FilterEdge02;
    public static javax.swing.JCheckBox FilterEdge03;
    public static javax.swing.JCheckBox FilterEdge04;
    public static javax.swing.JCheckBox FilterEdge05;
    public static javax.swing.JCheckBox FilterEdge06;
    public static javax.swing.JCheckBox FilterEdge07;
    public static javax.swing.JCheckBox FilterEdge08;
    public static javax.swing.JCheckBox FilterEdge09;
    public static javax.swing.JCheckBox FilterEdge10;
    public static javax.swing.JCheckBox FilterEdge11;
    public static javax.swing.JCheckBox FilterEdge12;
    public static javax.swing.JCheckBox FilterEdge13;
    public static javax.swing.JCheckBox FilterEdgeNeutral;
    public static javax.swing.JList FilterList;
    public static javax.swing.JCheckBox FilterNodeAgentButton;
    public static javax.swing.JCheckBox FilterNodeLonelyButton;
    private javax.swing.JButton G7Days;
    private javax.swing.JComboBox MouseModes;
    private javax.swing.JButton Reset;
    private javax.swing.JCheckBox ShowEdgeTextButton;
    public static javax.swing.JComboBox StatusFilterBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
