provenancedata(IDPARENT, IDPROVENANCEDATA, IDVERTEX, IDEDGE) :- vertex(IDPROVENANCEDATA, IDVERTEX), edge(IDPROVENANCEDATA, IDEDGE).
provenancedata(IDPARENT, IDPROVENANCEDATA, IDEDGE) :- edge(IDPROVENANCEDATA, IDEDGE).
provenancedata(IDPARENT, IDPROVENANCEDATA, IDVERTEX) :- vertex(IDPROVENANCEDATA, IDVERTEX).
edge(IDPARENT, IDEDGE, ID, TYPE, LABEL, VALUE, SOURCEID, TARGETID) :- id(IDEDGE, IDID,ID), type(IDEDGE, IDTYPE,TYPE), label(IDEDGE, IDLABEL,LABEL), value(IDEDGE, IDVALUE,VALUE), sourceid(IDEDGE, IDSOURCEID,SOURCEID), targetid(IDEDGE, IDTARGETID,TARGETID).
vertex(IDPARENT, IDVERTEX, ID, TYPE, LABEL, DATE, IDATTRIBUTE, DETAILS) :- id(IDVERTEX, IDID,ID), type(IDVERTEX, IDTYPE,TYPE), label(IDVERTEX, IDLABEL,LABEL), date(IDVERTEX, IDDATE,DATE), attribute(IDVERTEX, IDATTRIBUTE), details(IDVERTEX, IDDETAILS,DETAILS).
vertex(IDPARENT, IDVERTEX, ID, TYPE, LABEL, DATE, DETAILS) :- id(IDVERTEX, IDID,ID), type(IDVERTEX, IDTYPE,TYPE), label(IDVERTEX, IDLABEL,LABEL), date(IDVERTEX, IDDATE,DATE), details(IDVERTEX, IDDETAILS,DETAILS).
attribute(IDPARENT, IDATTRIBUTE, NAME, VALUE) :- name(IDATTRIBUTE, IDNAME,NAME), value(IDATTRIBUTE, IDVALUE,VALUE).
path(X, Y) :- path(X,Y,[]).
path(X,Y,_) :- edge(_, _, _, _, _, _, X, Y).
path(X,Y,V) :- \+ member(X, V), edge(_, _, _, _, _, _, X, Z), path(Z,Y, [X|V]).
filterlower(X, Y, Z) :- vertex(_, _, X, _, _, _, IDATTRIBUTE, _), attribute(_, IDATTRIBUTE, Y, VALUE), atom_number(VALUE, W), W < Z.
filtergreater(X, Y, Z) :- vertex(_, _, X, _, _, _, IDATTRIBUTE, _), attribute(_, IDATTRIBUTE, Y, VALUE), atom_number(VALUE, W), W > Z.
